### PR TITLE
feat: Go support

### PR DESCRIPTION
**Pull request by dontirun**

### CODE REVIEW

**Comment by ryparker** [comment]
Hey @dontirun It looks like the release workflow is failing due to a permission error when publishing for Go. Are you able to resolve this or provide some guidance?

**Comment by ryparker** [comment]
We will need to [revert](https://github.com/cdklabs/cdk-nag/pull/990) this PR since it is blocking the release workflow.

**Comment by dontirun** [comment]
It looks like the `cdklabs-automation` user needs to be invited to the the [cdk-nag-go](https://github.com/cdklabs/cdk-nag-go) as a collaborator

**Comment by dontirun** [comment]
I unfortunately do not have permissions to add `cdklabs-automation` as a collaborator to that repository

**Pull request merged**
